pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/vaibhaw491/Intelleje.git'
            }
        }
            stage('Unit Test') {
                steps {
                    dir('demo-counter-app-main') {
                        bat 'mvn test'
                    }
                }
            }

    }
}

