pipeline {
    agent any

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/vaibhaw491/Intelleje.git'
            }
        }
            stage('unit test') {
                    steps {
                       sh 'maven test'
                    }
                }
    }
}

